Feat: Plugin Store registry in JSON
sprinteins/oscd-plugin-store pull request #3
Opened 2024-10-22 15:43 UTC by rdsov

Implements:
- #1

2024-10-23 08:37 UTC, trusz commented on src/plugin-store.svelte
> +	});
```suggestion
	plugins.sort( (a,b) => a.name.localeCompare(b.name))
```

2024-10-23 08:37 UTC, trusz commented on src/plugin-store.svelte
>                  <Label>Restart</Label>
maybe "Reload App"?

2024-10-23 09:12 UTC, rdsov commented on src/plugin-store.svelte
> +	});
Done

2024-10-24 08:40 UTC, trusz commented on src/plugin-store.svelte
> +	const url = "https://sprinteins.github.io/oscd-plugin-store/plugins.json";
We can use a relative url, like how we load the styles.
Otherwise we always have to change this based on deployment.

2024-10-24 08:41 UTC, trusz commented on src/plugin-store.svelte
> +
How about we first sort by author then plugin name?
One would probably would like to see all the plugins from one author after each other

2024-10-24 08:42 UTC, trusz commented on src/plugin-store.svelte
> +	if (plugin.author) foundAuthor = plugin.author.toLowerCase().includes(search);
Nit: I would put a `{...}` around the code even in one-liner `ifs`

2024-10-24 08:45 UTC, trusz requested changes
just a few small changes :)

2024-10-24 11:58 UTC, tamasrusz commented on public/plugins.json
> +		},
This one is not ours

2024-10-24 12:03 UTC, tamasrusz approved these changes

2024-10-24 12:06 UTC, trusz approved these changes

2024-10-24 12:22 UTC, merged